---
- name: installing apache
  hosts: web
  user: root
  become: yes

  tasks:
  - name: install apache
    yum:
      name: httpd
      state: present
  - name: started apache
    service:
      name: httpd
      state: started
